# fly.toml file generated for billowing-water-131 on 2021-09-17T01:07:35Z

app = "billowing-water-131"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
